version: '3'

services:

  init:
    build: .
    image: netflixoss/aardvark:latest
    volumes:
      - data:/data
    env_file: .env
    command: [ "aardvark", "create_db" ]

  api:
    build: .
    image: netflixoss/aardvark:latest
    depends_on:
      - init
    ports:
      - "5000:5000"
    volumes:
      - data:/data
    environment:
      FLASK_APP: aardvark
      FLASK_ENV: development
    env_file: .env
    command: [ "flask", "run", "-h", "0.0.0.0", "-p", "5000" ]

  collector:
    build: .
    image: netflixoss/aardvark:latest
    depends_on:
      - init
    restart: always
    volumes:
      - data:/data
    env_file: .env
    command: [ "aardvark", "update", "-a", "$AARDVARK_ACCOUNTS" ]

volumes:
  data:
