version: '3'

services:

  init:
    build: .
    image: netflixoss/aardvark:latest
    volumes:
      - data:/data
      - ./settings.local.yaml.bak:/etc/aardvark/settings.local.yaml.bak
    env_file: .env
    command: [ "aardvark", "create_db" ]

  api:
    build: .
    image: netflixoss/aardvark:latest
    depends_on:
      - init
    ports:
      - 5000:5000
    volumes:
      - data:/data
      - ./settings.local.yaml.bak:/etc/aardvark/settings.local.yaml.bak
    env_file: .env
    command: [ "flask", "run", "-h", "0.0.0.0", "-p", "5000" ]

  collector:
    build: .
    image: netflixoss/aardvark:latest
    depends_on:
      - init
    restart: always
    volumes:
      - data:/data
      - ./settings.local.yaml.bak:/etc/aardvark/settings.local.yaml.bak
    env_file: .env
    command: [ "aardvark", "update" ]
    # If you're not using SWAG, you'll need to specify one or more accounts here:
    # command: [ "aardvark", "update", "-a", "123456789012", "-a", "234567890123" ]

volumes:
  data:
