[build-system]
requires = [
  "hatchling >=1.12.2",
  "hatch-vcs >=0.2.0",
]
build-backend = "hatchling.build"

[project]
name = "aardvark"
description = "A multi-account AWS IAM Access Advisor API"
readme = "README.md"
authors = [{name = "Netflix", email = "aardvark-maintainers@netflix.com"}]
license = {file = "LICENSE"}
requires-python = ">=3.8"
dependencies = [
    "asgiref",
    "blinker",
    "click",
    "cloudaux",
    "confuse",
    "dynaconf",
    "flasgger",
    "flask",
    "SQLAlchemy",
    "setuptools",
    "swag_client",
    "toml",
]
dynamic = ["version"]

[project.scripts]
aardvark = "aardvark.manage:cli"

[project.urls]
repository = "https://github.com/Netflix-Skunkworks/aardvark"

[tool.hatch.build]
include = ["aardvark", "README.md", "LICENSE", "aardvark/config_default.yaml"]

[tool.hatch.build.hooks.vcs]
version-file = "aardvark/__version__.py"

[tool.hatch.envs.test]
extra-dependencies = [
    "pytest",
    "pytest-asyncio",
]

[[tool.hatch.envs.test.matrix]]
python = ["3.8", "3.9", "3.10", "3.11"]

[tool.hatch.version]
source = "vcs"
scheme = "standard"

[tool.ruff.lint.per-file-ignores]
"**/tests/*" = ["ARG001", "ARG002", "PLR2004", "S101", "S105", "SLF001"]

[flake8]
max-line-length = 121
